#!/usr/bin/env node
// Exact Figma vector/text exports -> one RGB565-lossless indexed static image.
// The animated rail is deliberately NOT baked into the image.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const dir = resolve(root, 'components/ryz_system_ui');
// Crop the original whole-component export, not individual text ink boxes:
// this preserves Figma's fractional baselines and letter spacing exactly.
// The rail at y=234 is outside this static crop [24,12 .. 216,228).
const original = readFileSync(resolve(dir, 'assets/boot/screen.svg'), 'utf8');
if (!original.startsWith('<svg width="240" height="240"')) throw Error('Boot source must be the original 240x240 frame');
const svg = original.replace(/<svg\b[^>]*>/,
  '<svg xmlns="http://www.w3.org/2000/svg" width="192" height="216" viewBox="24 12 192 216">');
const png = spawnSync('rsvg-convert', [], { input: svg });
if (png.status !== 0) throw Error(png.stderr.toString());
const rgb = spawnSync('magick', ['png:-', '-alpha', 'off', '-depth', '8', 'rgb:-'], { input: png.stdout });
if (rgb.status !== 0) throw Error(rgb.stderr.toString());
if (rgb.stdout.length !== 192 * 216 * 3) throw Error('Unexpected raster size');
const palette = new Map();
const pixels = [];
for (let i = 0; i < rgb.stdout.length; i += 3) {
  const value = ((rgb.stdout[i] >> 3) << 11) | ((rgb.stdout[i + 1] >> 2) << 5) | (rgb.stdout[i + 2] >> 3);
  if (!palette.has(value)) palette.set(value, palette.size);
  if (palette.size > 256) throw Error('More than 256 RGB565 colors; do not silently quantize the artwork');
  pixels.push(palette.get(value));
}
// LVGL I8 palette is 256 little-endian ARGB8888 entries (BGRA bytes).
const data = Array(1024).fill(0);
for (const [value, index] of palette) {
  const r = (value >> 11) & 31, g = (value >> 5) & 63, b = value & 31;
  data.splice(index * 4, 4, (b << 3) | (b >> 2), (g << 2) | (g >> 4), (r << 3) | (r >> 2), 255);
}
data.push(...pixels);
const lines = [];
for (let i = 0; i < data.length; i += 24) lines.push('    ' + data.slice(i, i + 24).join(',') + ',');
writeFileSync(resolve(dir, 'ryz_v5_boot_asset.c'),
  '/* Generated by build_v5_boot_asset.mjs; exact Figma exports, RGB565-lossless. */\n' +
  '#include "lvgl.h"\n_Alignas(4) static const uint8_t pixels[] = {\n' + lines.join('\n') + '\n};\n' +
  'const lv_image_dsc_t ryz_v5_boot_asset = {\n' +
  '    .header = { .magic = LV_IMAGE_HEADER_MAGIC, .cf = LV_COLOR_FORMAT_I8,\n' +
  '                .w = 192, .h = 216, .stride = 192 },\n' +
  '    .data_size = sizeof(pixels), .data = pixels,\n};\n');
console.log(JSON.stringify({ width: 192, height: 216, colors: palette.size, bytes: data.length, rgb565Bytes: 192 * 216 * 2 }));
