#!/usr/bin/env node
// Offline exact local-Figma exports; not executable Monitor business logic.
// RGB565-lossless I8, one copy, no approximation or runtime SVG renderer.
import {readFileSync,writeFileSync} from 'node:fs';
import {spawnSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
const dir=fileURLToPath(new URL('../components/ryz_lvgl/',import.meta.url));
let out='/* Generated by tools/build_lua_ui_assets.mjs. */\n#include "ryz_lua_assets.h"\n';
for(const [name,w,h] of [['rootmaker_a_face',88,88],['monitor_divider',232,2]]) {
  let svg=readFileSync(dir+'assets/'+name+'.svg','utf8');
  // Figma's centered 1px stroke expands this 232x2 node to 233x3.
  // Crop its original half-pixel bounds, without rescaling the hatch pattern.
  if(name==='monitor_divider')svg=svg.replace(/<svg\b[^>]*>/,
    '<svg xmlns="http://www.w3.org/2000/svg" width="232" height="2" viewBox="0.5 0.5 232 2" fill="none">');
  const png=spawnSync('rsvg-convert',[],{input:svg});
  if(png.status) throw Error(png.stderr.toString());
  const rgb=spawnSync('magick',['png:-','-background','black','-alpha','remove','-alpha','off','-depth','8','rgb:-'],{input:png.stdout});
  if(rgb.status||rgb.stdout.length!==w*h*3) throw Error('Unexpected raster '+name);
  const palette=new Map(), pixels=[];
  for(let i=0;i<rgb.stdout.length;i+=3) {
    const v=((rgb.stdout[i]>>3)<<11)|((rgb.stdout[i+1]>>2)<<5)|(rgb.stdout[i+2]>>3);
    if(!palette.has(v))palette.set(v,palette.size);
    if(palette.size>256)throw Error('Refuse lossy quantization');
    pixels.push(palette.get(v));
  }
  const data=Array(1024).fill(0);
  for(const [v,i] of palette){const r=(v>>11)&31,g=(v>>5)&63,b=v&31;data.splice(i*4,4,(b<<3)|(b>>2),(g<<2)|(g>>4),(r<<3)|(r>>2),255);}
  data.push(...pixels);
  out+='static const uint8_t '+name+'_pixels[] = {\n';
  for(let i=0;i<data.length;i+=24)out+='    '+data.slice(i,i+24).join(',')+',\n';
  out+='};\nconst lv_image_dsc_t ryz_lua_'+name+' = {\n'+
    '    .header = {.magic=LV_IMAGE_HEADER_MAGIC,.cf=LV_COLOR_FORMAT_I8,.w='+w+',.h='+h+',.stride='+w+'},\n'+
    '    .data_size=sizeof('+name+'_pixels),.data='+name+'_pixels,\n};\n';
  console.log(name+': '+w+'x'+h+', '+palette.size+' colors, '+data.length+' bytes');
}
const path=dir+'ryz_lua_assets.c';
if(process.argv.includes('--check')){if(readFileSync(path,'utf8')!==out)throw Error('Stale Lua UI assets');}
else writeFileSync(path,out);
