#!/usr/bin/env python3
"""Deterministically pack offline web sources and audited WOFF2 into C.

The checked-in C is consumed directly by target and host builds. No Node/web
toolchain, CDN or network access is required when building firmware.
"""
import argparse
import base64
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REPO = ROOT.parents[1]
COMPONENT = ROOT / "components/ryz_provisioning"
SOURCE = COMPONENT / "web"


def literal(name, value):
    return "const char " + name + "[] =\n" + "\n".join(
        json.dumps(line, ensure_ascii=True).replace("?", "\\?") for line in value.splitlines(keepends=True)
    ) + ";\n"


def generate():
    css = (SOURCE / "shared.css").read_text()
    for family, filename, license_name, weight in [
        ("Noto Sans", "noto-sans-015.woff2", "OFL-NotoSans.txt", "400 700"),
        ("Teko", "teko-119.woff2", "OFL-Teko.txt", "500 700"),
    ]:
        font = REPO / "assets/typography/src/assets/fonts" / filename
        license_text = (REPO / "assets/typography/public/fonts" / license_name).read_text()
        css += "\n/* " + license_text.replace("*/", "* /") + " */\n"
        css += "@font-face{font-family:'" + family + "';font-style:normal;font-weight:" + weight
        css += ";font-display:swap;src:url(data:font/woff2;base64," + base64.b64encode(font.read_bytes()).decode()
        css += ") format('woff2')}\n"
    result = '#include "ryz_provisioning_portal.h"\n/* Generated by tools/generate_provisioning_web.py. Edit web/ sources. */\n'
    result += literal("ryz_provisioning_web_css", css)
    for stem, name in [("provision", "ryz_provisioning_portal_html"), ("diagnostics", "ryz_diagnostics_html")]:
        html = (SOURCE / (stem + ".html")).read_text().replace(
            "@@STYLE@@", (SOURCE / (stem + ".css")).read_text()).replace(
            "@@SCRIPT@@", (SOURCE / (stem + ".js")).read_text())
        result += literal(name, html)
    return result


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    output = COMPONENT / "ryz_provisioning_portal.c"
    result = generate()
    if args.check:
        if not output.exists() or output.read_text() != result:
            raise SystemExit("WEB_ASSETS_STALE: run tools/generate_provisioning_web.py")
    else:
        output.write_text(result)
    print("PROVISIONING_WEB_ASSETS_READY", len(result.encode()))


if __name__ == "__main__":
    main()
