/* Browser fixtures deliberately use SAMPLE data. Server renders the exact C
 * payload linked into firmware, not a hand-maintained preview HTML copy. */
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const http = require('node:http');
const child = require('node:child_process');
const {chromium} = require(process.env.RYZ_PLAYWRIGHT_MODULE || 'playwright');
const root = path.resolve(__dirname,'..');
const out = path.resolve(root,'../../docs/software/evidence/v5-web-sync-20260913');
const temp = fs.mkdtempSync(path.join(os.tmpdir(),'ryz-web-'));
const fixtureSource = '#include <stdio.h>\n#include <string.h>\n#include "ryz_provisioning_portal.h"\nint main(int argc,char **argv){if(argc!=2)return 2;fputs(!strcmp(argv[1],"css")?ryz_provisioning_web_css:!strcmp(argv[1],"fault")?ryz_diagnostics_html:ryz_provisioning_portal_html,stdout);return 0;}\n';
fs.writeFileSync(path.join(temp,'dump.c'),fixtureSource);
child.execFileSync('cc',['-std=c11','-I',path.join(root,'components/ryz_provisioning'),path.join(root,'components/ryz_provisioning/ryz_provisioning_portal.c'),path.join(temp,'dump.c'),'-o',path.join(temp,'dump')]);
const payload = Object.fromEntries(['css','fault','provision'].map(name=>[name,child.execFileSync(path.join(temp,'dump'),[name])]));
const networks=[['STUDIO_2G','WPA2',6,-41],['RYZOBEE_LAB','WPA2',1,-51],['MAKERSPACE','WPA3',11,-61],['DEV_24','OPEN',3,-71],['MOBILE_HOTSPOT','WPA2',9,-76]].map(([ssid,auth,channel,rssi])=>({ssid,auth,channel,rssi}));
const statusBase={state:'AP_READY',portal_ip:'192.168.4.1',portal_active:true,ap_ssid:'RYZOBEE-A1B2',session:'RZB-A1B2',portal_session_elapsed_s:120,scan_state:'ready',scan_revision:1,scan_total:5,scan_count:5,networks,scan_channels:[1,3,6,9,11],scan_rssi_min:-76,scan_rssi_max:-41,scan_elapsed_ms:800,credentials_stored:false};
let state={...statusBase},reportStatus=200,delay=0,posts=[],diagnosticRequests=[];
const reportBase={id:'00000001',phase:'runtime',code:'LUA-R01',summary:'Runtime error',source_file:'sample_sensor.lua',job_id:'SAMPLE-17',firmware_version:'0.9.0 / SAMPLE',line:42,duration_ms:1284,peak_bytes:81920,error:'sample_sensor.lua:42: attempt to index a nil value (local "sample")',output:'[SAMPLE] captured output\n[WARN] sample unavailable\n[ERROR] attempt to read nil\n--- captured output ends ---',error_truncated:false,output_truncated:true,lua_ok:false,ok:false,cleanup_ok:true,trace:null};
let report={...reportBase};
const server=http.createServer(async(req,res)=>{const pathname=req.url.split('?')[0];res.setHeader('Cache-Control','no-store');if(req.method==='POST'){let body='';for await(const chunk of req)body+=chunk;posts.push({path:pathname,body:JSON.parse(body||'{}')});if(pathname==='/api/provision')state={...state,state:'CONNECTING',sta_ssid:JSON.parse(body).ssid,connect_progress:32,connect_timeout_remaining_s:46};if(pathname==='/api/cancel')state={...state,state:'AP_READY'};res.setHeader('Content-Type','application/json');res.end('{"accepted":true}');return;}if(pathname==='/api/status'){res.setHeader('Content-Type','application/json');res.end(JSON.stringify(state));return;}if(pathname.startsWith('/api/diagnostics/')){diagnosticRequests.push(req.url);if(delay)await new Promise(resolve=>setTimeout(resolve,delay));res.statusCode=reportStatus;res.setHeader('Content-Type','application/json');res.end(JSON.stringify(reportStatus===200?report:{error:'report_unavailable'}));return;}res.setHeader('Content-Type',pathname==='/assets/ryz-web.css'?'text/css':'text/html');res.end(pathname==='/assets/ryz-web.css'?payload.css:pathname.startsWith('/f/')?payload.fault:payload.provision);});
let browser;
async function ready(page){await page.evaluate(()=>document.fonts.ready);assert.ok(await page.evaluate(()=>document.fonts.check('18px "Noto Sans"')&&document.fonts.check('30px "Teko"')));await page.waitForTimeout(100);}
async function checkWidth(page){const result=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth}));assert.ok(result.scroll<=result.width,JSON.stringify(result));}
async function screenshot(page,name){await ready(page);await checkWidth(page);await page.screenshot({path:path.join(out,name+'.png'),fullPage:true});}
async function main(){
  fs.mkdirSync(out,{recursive:true});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const origin='http://127.0.0.1:'+server.address().port;
  browser=await chromium.launch({headless:true,...(process.env.RYZ_CHROMIUM?{executablePath:process.env.RYZ_CHROMIUM}:{})});const desktop=await browser.newContext({viewport:{width:1440,height:1080}}),page=await desktop.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto(origin);await page.waitForSelector('.network-row');await ready(page);
  assert.equal(await page.locator('.network-row').count(),5);assert.equal(await page.locator('.network-list').evaluate(el=>el.clientHeight),448);
  await page.getByRole('button',{name:'STUDIO_2G WPA2 channel 6',exact:true}).click();await page.locator('#password').fill('samplekey');await screenshot(page,'provision-desktop-select');
  const centered=await page.locator('#filter').evaluate(el=>{const child=el.querySelector('.desktop-only'),a=el.getBoundingClientRect(),b=child.getBoundingClientRect();return Math.abs((a.top+a.bottom)/2-(b.top+b.bottom)/2);});assert.ok(centered<1,'filter vertical center '+centered);
  await page.locator('#connect').click();await page.waitForSelector('#view-joining.active');assert.equal(posts.filter(p=>p.path==='/api/provision').length,1);assert.equal(await page.locator('.network-row:enabled').count(),0);await screenshot(page,'provision-desktop-joining');await page.locator('#cancel').click();await page.waitForSelector('#view-select.active');assert.equal(posts.filter(p=>p.path==='/api/cancel').length,1);
  for(const kind of ['READY','FAILED']){state={...statusBase,state:kind==='READY'?'ONLINE':'FAILED',sta_ssid:'STUDIO_2G',ipv4:'192.168.1.64',error_code:'E_WIFI_AUTH'};await page.reload();await page.waitForSelector(kind==='READY'?'#view-ready.active':'#view-failed.active');await screenshot(page,'provision-desktop-'+kind.toLowerCase());}
  const mobile=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),phone=await mobile.newPage();phone.on('pageerror',e=>errors.push(e.message));
  for(const [kind,radio]of [['select','AP_READY'],['joining','CONNECTING'],['ready','ONLINE'],['failed','FAILED']]){state={...statusBase,state:radio,sta_ssid:'STUDIO_2G',ipv4:'192.168.1.64',error_code:'E_WIFI_AUTH',connect_progress:62,connect_timeout_remaining_s:46};await phone.goto(origin);await phone.waitForSelector('#view-'+kind+'.active');await phone.waitForSelector('.network-row');if(kind==='select'){await phone.locator('.network-row').first().click();await phone.locator('#password').fill('samplekey');}await screenshot(phone,'provision-mobile-'+kind);assert.equal(await phone.locator('.network-list').evaluate(el=>el.clientHeight),264);assert.equal(await phone.locator('.network-row').count(),5);}
  state={...statusBase,networks:[...networks,...Array.from({length:7},(_,i)=>({ssid:'SAMPLE_LONG_NETWORK_'+i+'_路由器',auth:'WPA2',channel:i+1,rssi:-60}))],scan_total:12};await phone.goto(origin);await phone.waitForSelector('.network-row');await phone.locator('.network-row').first().click();await phone.locator('#password').fill('samplekey');const list=phone.locator('#network-list');await list.evaluate(el=>el.scrollTop=el.scrollHeight);const scrollBefore=await list.evaluate(el=>el.scrollTop);await phone.waitForTimeout(1200);assert.equal(await list.evaluate(el=>el.scrollTop),scrollBefore,'poll must not reset list');assert.equal(await phone.locator('.network-row.selected').count(),1);await screenshot(phone,'provision-mobile-long-list');
  await phone.evaluate(()=>window.scrollTo(0,0));await list.evaluate(el=>el.scrollTop=0);const cdp=await mobile.newCDPSession(phone);const box=await list.boundingBox();
  async function swipe(x,from,to){await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y:from}]});for(let i=1;i<=12;i++){await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x,y:from+(to-from)*i/12}]});await phone.waitForTimeout(20);}await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await phone.waitForTimeout(400);}
  await swipe(box.x+140,box.y+220,box.y+30);assert.ok(await list.evaluate(el=>el.scrollTop)>0,'real touch scrolls inner list');assert.equal(await phone.evaluate(()=>scrollY),0,'inner gesture must not move outer page');assert.equal(await phone.locator('.network-row.selected .ssid').textContent(),'STUDIO_2G','drag must not select another network');await list.evaluate(el=>el.scrollTop=el.scrollHeight);await swipe(box.x+140,box.y+220,box.y+30);assert.equal(await phone.evaluate(()=>scrollY),0,'inner edge must not hand gesture to page');const atEnd=await list.evaluate(el=>el.scrollTop);await swipe(220,570,320);assert.ok(await phone.evaluate(()=>scrollY)>0,'outside gesture scrolls outer page');assert.equal(await list.evaluate(el=>el.scrollTop),atEnd,'outside gesture must not move list');await cdp.detach();
  await phone.setViewportSize({width:320,height:844});await screenshot(phone,'provision-mobile-320');await phone.setViewportSize({width:390,height:844});
  const fault=origin+'/f/00000001?cap=0123456789abcdef0123456789abcdef';
  await page.goto(fault);await page.waitForSelector('#report-view:not([hidden])');await screenshot(page,'diagnostics-desktop');await phone.goto(fault);await phone.waitForSelector('#report-view:not([hidden])');await screenshot(phone,'diagnostics-mobile');assert.equal(await page.locator('#raw-error').textContent(),await phone.locator('#raw-error').textContent());assert.equal(await page.locator('#output').textContent(),await phone.locator('#output').textContent());assert.equal(await phone.locator('.output-content').evaluate(el=>getComputedStyle(el).overflowY),'visible');
  report={...reportBase,source_file:'SAMPLE_'+'LongFile'.repeat(20)+'.lua',error:'<script>window.INJECTED=true</script>\n'+'NO_SPACE_'.repeat(120),output:'[SAMPLE] '+Array.from({length:70},(_,i)=>'line '+i+' x'.repeat(30)).join('\n')+'\nCAPTURE_END',cleanup_ok:null,peak_bytes:null,line:null};await page.reload();await phone.reload();await page.waitForSelector('#report-view:not([hidden])');await phone.waitForSelector('#report-view:not([hidden])');assert.equal(await page.evaluate(()=>window.INJECTED),undefined);await page.locator('.output-content').evaluate(el=>el.scrollTop=el.scrollHeight);await page.locator('.error-content').evaluate(el=>el.scrollTop=el.scrollHeight);await screenshot(page,'diagnostics-desktop-long');await screenshot(phone,'diagnostics-mobile-long');assert.equal(await phone.locator('[data-field="cleanup_ok"]').textContent(),'--');
  const downloadWait=phone.waitForEvent('download');await phone.locator('[data-action="download"]').first().click();const download=await downloadWait;const saved=await download.path();const downloaded=fs.readFileSync(saved,'utf8');assert.ok(downloaded.includes(report.error)&&downloaded.includes('CAPTURE_END'));assert.ok(!downloaded.includes('cap=')&&!downloaded.includes('0123456789abcdef'));
  report={...reportBase,output:'',output_truncated:false};await phone.reload();await phone.waitForSelector('#empty-output:not([hidden])');await screenshot(phone,'diagnostics-mobile-empty');
  reportStatus=410;await phone.reload();await phone.waitForSelector('#recover:not([hidden])');await screenshot(phone,'diagnostics-mobile-expired');await phone.locator('#retry-load').click();await phone.waitForSelector('#recover:not([hidden])');assert.ok(diagnosticRequests.every(url=>url==='/api/diagnostics/00000001?cap=0123456789abcdef0123456789abcdef'));
  reportStatus=503;await phone.reload();await phone.getByRole('heading',{name:'LOCAL LINK OFFLINE'}).waitFor();await screenshot(phone,'diagnostics-mobile-offline');
  delay=2000;reportStatus=200;await phone.reload();await phone.getByRole('heading',{name:'LOADING CAPTURE'}).waitFor();await screenshot(phone,'diagnostics-mobile-loading');await phone.waitForSelector('#report-view:not([hidden])');delay=0;
  assert.deepEqual(errors,[]);console.log('PROVISIONING_WEB_PASS exact_c_payload fonts 4_desktop 4_mobile min320 list_persistence joining_lock cancel filter_center diagnostics_identity unknown xss long_scroll download empty expired offline loading');
}
main().catch(error=>{console.error(error);process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();server.close();fs.rmSync(temp,{recursive:true,force:true});});
