'use strict';
const $=id=>document.getElementById(id);
const match=location.pathname.match(/^\/f\/([0-9a-f]{8})$/);
const id=match?match[1]:'';
const cap=new URLSearchParams(location.search).get('cap')||'';
const endpoint=id&&/^[0-9a-f]{32}$/.test(cap)?'/api/diagnostics/'+id+'?cap='+encodeURIComponent(cap):null;
let report=null,loading=false;
function field(name,value){document.querySelectorAll('[data-field="'+name+'"]').forEach(e=>e.textContent=value===null||value===undefined||value===''?'--':String(value));}
field('id',id||'--');
function state(kind){
  $('report-view').hidden=true;$('status-view').hidden=false;$('status-view').dataset.state=kind;
  $('recover').hidden=kind!=='expired';$('retry-hint').hidden=kind!=='expired';$('expired-title').hidden=kind!=='expired';
  $('retry-load').hidden=kind==='loading';$('status-footer').hidden=kind!=='loading';
  const copy={loading:['LOADING CAPTURE','Waiting for the device to return this report. Content appears only after the snapshot is received.'],offline:['LOCAL LINK OFFLINE','The page cannot reach the device. Check Wi-Fi or the protected device AP, then retry this report link.'],expired:['REPORT UNAVAILABLE','The device no longer has this report. It may have restarted, replaced the capture, or closed the local session.']};
  $('status-title').textContent=copy[kind][0];$('status-description').textContent=copy[kind][1];
  $('retry-load').textContent=kind==='expired'?'CHECK THIS LINK AGAIN':'RETRY CONNECTION';
}
function render(value){report=value;for(const name of ['id','phase','code','summary','source_file','job_id','firmware_version','line'])field(name,value[name]);field('duration_ms',Number.isFinite(value.duration_ms)?value.duration_ms.toLocaleString()+' ms':null);field('peak_bytes',Number.isFinite(value.peak_bytes)?(value.peak_bytes/1024).toFixed(1)+' KiB':null);field('cleanup_ok',value.cleanup_ok===true?'No cleanup error':value.cleanup_ok===false?'Cleanup failed':null);field('lua_ok',value.lua_ok===true?'Passed':value.lua_ok===false?'Failed':null);field('ok',value.ok===true?'Passed':value.ok===false?'Failed':null);$('raw-error').textContent=value.error||'--';$('trace').textContent=value.trace||'TRACE NOT CAPTURED';$('output').textContent=value.output||'';$('output-content').hidden=!value.output;$('empty-output').hidden=!!value.output;$('output-limit').hidden=!value.output_truncated;$('error-limit').hidden=!value.error_truncated;$('encoding-note').hidden=!value.text_sanitized;$('status-view').hidden=true;$('report-view').hidden=false;$('local-address').textContent='LOCAL LINK · '+location.hostname+' / NO CLOUD UPLOAD';}
async function load(){if(loading)return;if(!endpoint){state('expired');return;}loading=true;state('loading');const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),8000);try{const response=await fetch(endpoint,{cache:'no-store',credentials:'omit',referrerPolicy:'no-referrer',signal:controller.signal});if([400,403,404,410].includes(response.status)){report=null;state('expired');return;}if(!response.ok)throw Error('unavailable');const value=await response.json();if(value.id!==id)throw Error('report identity changed');render(value);}catch{state('offline');}finally{clearTimeout(timer);loading=false;}}
function textReport(){if(!report)return'';const r=report,unknown=v=>v===null||v===undefined?'--':String(v);return['RYZOBEE / CAPTURED REPORT '+r.id,'STATIC SNAPSHOT / NOT LIVE','SOURCE FILE: '+unknown(r.source_file),'JOB ID: '+unknown(r.job_id),'FIRMWARE: '+unknown(r.firmware_version),'PHASE: '+unknown(r.phase),'CODE: '+unknown(r.code),'LINE: '+unknown(r.line),'ELAPSED MS: '+unknown(r.duration_ms),'PEAK BYTES: '+unknown(r.peak_bytes),'LUA OK: '+unknown(r.lua_ok),'OVERALL OK: '+unknown(r.ok),'CLEANUP OK: '+unknown(r.cleanup_ok),'ERROR TRUNCATED: '+Boolean(r.error_truncated),'OUTPUT TRUNCATED: '+Boolean(r.output_truncated),'INVALID UTF-8 REPLACED: '+Boolean(r.text_sanitized),'','CAPTURED ERROR',r.error||'--','','TRACE',r.trace||'-- (not captured)','','CAPTURED OUTPUT',r.output||'-- (no captured output)','','Temporary local capture. Scrub secrets before sharing.'].join('\n');}
async function copy(text){try{if(navigator.clipboard&&window.isSecureContext)await navigator.clipboard.writeText(text);else{const area=document.createElement('textarea');area.value=text;area.readOnly=true;area.style.position='fixed';area.style.left='-10000px';document.body.append(area);area.select();const ok=document.execCommand('copy');area.remove();if(!ok)throw Error('copy');}$('action-status').textContent='COPIED TO CLIPBOARD';}catch{$('action-status').textContent='COPY UNAVAILABLE · use DOWNLOAD .TXT instead.';}}
document.querySelectorAll('[data-action]').forEach(button=>button.addEventListener('click',()=>{if(!report)return;const action=button.dataset.action;if(action==='copy-error')copy(report.error||'--');else if(action==='copy-report')copy(textReport());else{const blob=new Blob([textReport()],{type:'text/plain;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='ryzobee-report-'+id+'.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('action-status').textContent='REPORT DOWNLOAD REQUESTED';}}));
$('retry-load').addEventListener('click',load);load();
