/* Only the C provisioning service owns radio configuration and saved keys. */
'use strict';
const $ = id => document.getElementById(id);
const model = {status:null,networks:[],selected:null,visible:'select',busy:false,online:false,scanRequested:false,scanKey:'',editFailure:false,requesting:false,drag:null};
const kindOf = state => state === 'ONLINE' ? 'ready' : ['CONNECTING','CREDENTIALS_RECEIVED'].includes(state) ? 'joining' : state === 'FAILED' ? 'failed' : 'select';
const networkKey = n => JSON.stringify([n.ssid,n.auth,n.channel]);
const age = seconds => {const n=Math.max(0,Number(seconds)||0);return String(Math.floor(n/60)).padStart(2,'0')+':'+String(n%60).padStart(2,'0');};
const keyBytes = value => new TextEncoder().encode(value).length;
const secured = () => model.selected && model.selected.auth !== 'OPEN';
const locked = () => model.busy || model.visible === 'joining' || model.visible === 'ready' || !model.online;
function syncControls(){
  const key=$('password').value,n=model.selected,valid=n&&keyBytes(n.ssid)<=32&&(!secured()||(keyBytes(key)>=8&&keyBytes(key)<=63));
  $('connect').disabled=locked()||!valid;$('retry').disabled=locked()||!valid;
  $('rescan').disabled=locked();$('rescan-mobile').disabled=locked();$('change').disabled=model.busy||!model.online;
  $('cancel').disabled=model.busy||!model.online;
  document.querySelectorAll('.network-row').forEach(row=>row.disabled=locked());
}
function selectNetwork(n){if(locked())return;model.selected=n;model.editFailure=true;$('password').value='';$('manual-ssid').value='';maskPassword();showSelection();renderRows();setView('select');syncControls();}
function showSelection(){const n=model.selected;const title=n?n.ssid:'SELECT A NETWORK',meta=n?(n.auth||'OPEN')+' · CH '+(n.channel||'--')+' · 2.4 GHz':'CH -- · 2.4 GHz';$('selected-ssid').textContent=title;$('selected-network-meta').textContent=meta;$('selected-meta').textContent=n?title+' / '+(n.auth||'OPEN')+' / CH '+(n.channel||'--'):title;$('scan-selected').textContent=n?'SELECTED '+title:title;$('selection-chip').textContent=n?'SELECTED':'SELECT';$('password').disabled=n&&n.auth==='OPEN';}
function renderRows(){
  const list=$('network-list'),top=list.scrollTop;list.replaceChildren();
  if(!model.networks.length){const empty=document.createElement('div');empty.className='empty-row';empty.textContent=['running','queued'].includes(model.status?.scan_state)?'SCANNING 2.4G CHANNELS...':'NO NETWORKS · ENTER SSID BELOW';list.append(empty);}
  for(const n of model.networks){const row=document.createElement('button');row.type='button';row.className='network-row'+(model.selected&&networkKey(model.selected)===networkKey(n)?' selected':'');row.setAttribute('aria-pressed',String(row.classList.contains('selected')));row.setAttribute('aria-label',n.ssid+' '+n.auth+' channel '+n.channel);row.disabled=locked();const bar=document.createElement('span');bar.className='bar';const info=document.createElement('span'),name=document.createElement('span'),meta=document.createElement('span');name.className='ssid';name.textContent=n.ssid;meta.className='meta';meta.textContent=(n.auth||'OPEN')+' · CH '+n.channel+' · 2.4 GHz';info.append(name,meta);const signal=document.createElement('span');signal.className='signal';signal.setAttribute('aria-label',Number.isFinite(n.rssi)?n.rssi+' dBm':'Signal unavailable');const count=!Number.isFinite(n.rssi)?0:n.rssi>=-50?4:n.rssi>=-65?3:n.rssi>=-75?2:1;for(let i=0;i<4;i++){const b=document.createElement('i');b.className=i<count?'on':'';signal.append(b);}row.append(bar,info,signal);row.addEventListener('click',e=>{if(model.drag?.moved){e.preventDefault();return;}selectNetwork(n);});list.append(row);}
  list.scrollTop=top;
}
function setView(kind){if(model.visible!==kind)maskPassword();model.visible=kind;document.querySelectorAll('.state-view').forEach(v=>v.classList.toggle('active',v.id==='view-'+kind));const active=kind==='select'?'scan':kind==='ready'?'ready':'link';document.querySelectorAll('[data-step]').forEach(el=>{const step=el.dataset.step;el.className=kind==='failed'&&step==='link'?'fail':step===active?'active':kind!=='select'&&['scan','key'].includes(step)||kind==='ready'?'done':'';});}
function render(s){
  const prior=model.status;model.status=s;model.online=true;
  if(s.state!=='FAILED')model.editFailure=false;
  const state=kindOf(s.state),kind=state==='failed'&&model.editFailure?'select':state;setView(kind);
  const incoming=(Array.isArray(s.networks)?s.networks:[]).filter(n=>n&&typeof n.ssid==='string'&&n.ssid&&Number(n.channel)>=1&&Number(n.channel)<=14);
  const signature=JSON.stringify(incoming),changed=signature!==model.scanKey;
  if(changed){model.scanKey=signature;model.networks=incoming;if(model.selected&&!model.selected.manual&&!incoming.some(n=>networkKey(n)===networkKey(model.selected))&&kind==='select'){model.selected=null;$('password').value='';$('feedback').textContent='The selected network changed. Select it again.';}renderRows();}
  if(!prior||prior.scan_state!==s.scan_state)renderRows();
  const session=s.session||'--',ip=s.portal_ip||'--',busyScan=['running','queued'].includes(s.scan_state);$('session').textContent=session;$('session-mobile').textContent=session.replace(/^RZB-/,'');$('footer-session').textContent=session;$('ap-ip').textContent=ip;$('ap-ip-mobile').textContent=ip;$('footer-local').textContent=ip+' / LOCAL';$('session-age').textContent=age(s.portal_session_elapsed_s);$('device-online').textContent=s.portal_active?'● AP ONLINE':'AP INACTIVE';
  const retained=model.networks.length,total=Math.max(retained,Number(s.scan_total)||0);$('scan-count').textContent=busyScan?'SCANNING...':String(retained).padStart(2,'0')+' FOUND'+(total>retained?' / '+total+' DETECTED':'');$('scan-note').textContent=s.scan_state==='failed'?'Scan unavailable · enter the SSID manually.':total>retained?'Showing '+retained+' of '+total+' detected networks. Rescan to refresh.':'2.4 GHz only · scroll networks';$('channels').textContent='CHANNELS '+((s.scan_channels||[]).join(' / ')||'--');$('rssi-range').textContent=Number.isFinite(s.scan_rssi_min)?'RSSI RANGE '+s.scan_rssi_min+' → '+s.scan_rssi_max+' dBm':'RSSI RANGE --';$('manual-wrap').hidden=!!retained||busyScan;
  showSelection();
  const progress=Number.isFinite(s.connect_progress)?Math.min(100,Math.max(0,s.connect_progress)):null;$('progress').textContent=progress===null?'--':progress+'%';$('ring').style.setProperty('--progress',(progress||0)+'%');$('progress-line').style.width=(progress||0)+'%';$('joining-ssid').textContent=s.sta_ssid||model.selected?.ssid||'--';$('joining-log').textContent='Waiting for network confirmation · '+(s.connect_timeout_remaining_s??'--')+' s remaining.';$('ready-ssid').textContent=s.sta_ssid||'--';$('ready-ip').textContent='IPv4 '+(s.ipv4||'--');
  /* ONLINE proves STA + IP, not a dashboard/HTTP service at that address. */
  $('dashboard').disabled=true;
  const error=s.error_code||'E_WIFI_CONNECT',timeout=error==='E_WIFI_TIMEOUT',missing=error==='E_WIFI_NOT_FOUND',auth=error==='E_WIFI_AUTH';$('error-code').textContent=error;$('error-status').textContent=timeout?'CONNECTION TIMEOUT':missing?'NETWORK NOT FOUND':auth?'AUTHENTICATION REJECTED':'CONNECTION FAILED';$('diagnostic-cause').textContent=timeout?'Router did not answer before the deadline.':missing?'Selected network was not found on 2.4 GHz.':auth?'Password may be incorrect.':'Check router availability and connection settings.';$('credential-policy').textContent=s.credentials_stored?'Credentials are retained on this device.':'No credential was stored.';
  const title=kind==='ready'?'READY':kind==='joining'?'CONNECTING':kind==='failed'?'FAILED':'STANDBY';$('telemetry-title').textContent=title;$('telemetry-chip').textContent=kind==='ready'?'ONLINE':kind==='joining'?'LINKING':kind==='failed'?'FAILED':'IDLE';$('telemetry-chip').className='chip '+(kind==='ready'?'green':kind==='failed'?'red':'');$('metric-rssi').textContent=Number.isFinite(s.ap_rssi_dbm)?s.ap_rssi_dbm+' dBm':'--';$('metric-scan').textContent=Number(s.scan_elapsed_ms)>0?(s.scan_elapsed_ms/1000).toFixed(1)+' s':'--';$('metric-dhcp').textContent=kind==='ready'?'DONE':'--';$('metric-timeout').textContent=kind==='joining'?(s.connect_timeout_remaining_s??'--')+' s':'--';const message=kind==='ready'?'DHCP lease acquired · device online':kind==='failed'?error:busyScan?'Scanning supported networks.':'Waiting for credentials.';$('telemetry-log').textContent=message;$('telemetry-log').classList.toggle('error',kind==='failed');$('footer-log').textContent=message;$('footer-state').textContent=kind==='joining'?'TIMEOUT '+(s.connect_timeout_remaining_s??'--')+'s':kind==='ready'?'ONLINE':kind==='failed'?error:'SESSION '+age(s.portal_session_elapsed_s);
  const segments={select:['orange','','',''],joining:['','orange','orange',''],ready:['on','on','on','on'],failed:['on','on','red','']};document.querySelectorAll('#telemetry-segments i').forEach((e,i)=>e.className=segments[kind][i]);syncControls();
}
async function request(url,body){const abort=new AbortController(),timeout=setTimeout(()=>abort.abort(),8000);try{const r=await fetch(url,{method:body===undefined?'GET':'POST',cache:'no-store',headers:body===undefined?{}:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body),signal:abort.signal});if(!r.ok)throw Error('Device request rejected ('+r.status+').');return r;}finally{clearTimeout(timeout);}}
async function poll(){if(model.requesting)return;model.requesting=true;try{const r=await request('/api/status');render(await r.json());if(!model.scanRequested&&model.status.scan_state==='idle'){model.scanRequested=true;await request('/api/scan',{});}}catch(e){model.online=false;$('feedback').textContent='LOCAL LINK OFFLINE · reconnect to the device network.';$('telemetry-log').textContent='Portal link unavailable.';syncControls();}finally{model.requesting=false;}}
async function scan(){if(locked())return;model.busy=true;model.scanRequested=true;syncControls();try{await request('/api/scan',{});$('feedback').textContent='';}catch(e){$('feedback').textContent=e.message;}finally{model.busy=false;await poll();syncControls();}}
async function submit(){syncControls();if($('connect').disabled)return;model.busy=true;syncControls();try{await request('/api/provision',{ssid:model.selected.ssid,password:secured()?$('password').value:''});model.editFailure=false;setView('joining');maskPassword();$('feedback').textContent='';}catch(e){$('feedback').textContent=e.message;}finally{model.busy=false;await poll();syncControls();}}
async function cancel(){if(model.busy||!model.online)return;model.busy=true;syncControls();try{await request('/api/cancel',{});model.selected=null;model.editFailure=false;$('password').value='';$('manual-ssid').value='';setView('select');$('feedback').textContent='';}catch(e){$('feedback').textContent=e.message;}finally{model.busy=false;await poll();syncControls();}}
function maskPassword(){$('password').type='password';$('show-password').textContent='SHOW';$('show-password').setAttribute('aria-label','Show password');$('password-state').textContent='MASKED';}
$('password').addEventListener('input',syncControls);$('manual-ssid').addEventListener('input',()=>{const ssid=$('manual-ssid').value;model.selected=ssid?{ssid,auth:'WPA2',channel:'--',manual:true}:null;showSelection();syncControls();});$('show-password').onclick=()=>{const show=$('password').type==='password';$('password').type=show?'text':'password';$('show-password').textContent=show?'HIDE':'SHOW';$('show-password').setAttribute('aria-label',show?'Hide password':'Show password');$('password-state').textContent=show?'VISIBLE':'MASKED';};document.addEventListener('visibilitychange',()=>{if(document.hidden)maskPassword();});window.addEventListener('blur',maskPassword);
$('connect').onclick=submit;$('retry').onclick=submit;$('cancel').onclick=cancel;$('rescan').onclick=scan;$('rescan-mobile').onclick=scan;$('change').onclick=()=>{if(locked())return;model.editFailure=true;model.selected=null;$('password').value='';showSelection();renderRows();setView('select');syncControls();};document.addEventListener('keydown',e=>{if(e.key==='Escape'&&model.visible==='joining')cancel();});
/* Keep each pointer gesture in its original scroll owner. A drag never selects. */
const list=$('network-list');list.addEventListener('pointerdown',e=>{model.drag={id:e.pointerId,x:e.clientX,y:e.clientY,moved:false};});list.addEventListener('pointermove',e=>{const d=model.drag;if(d&&d.id===e.pointerId&&Math.hypot(e.clientX-d.x,e.clientY-d.y)>8)d.moved=true;});list.addEventListener('pointercancel',()=>{if(model.drag)model.drag.moved=true;});list.addEventListener('scroll',()=>{if(model.drag)model.drag.moved=true;},{passive:true});
setInterval(poll,1000);poll();
