/* Offline generator only. Reuses the exact production FreeType/subset path,
 * so line metrics, hinting, advance and A8 coverage do not change in V5. */
#include <assert.h>
#include <stdio.h>
#include <stdint.h>
#include "ryz_font.h"

#ifdef NDEBUG
#error "The font generator requires assertions"
#endif

static const struct { ryz_font_face_t face; unsigned px; } palette[] = {
#define FONT(face, px) {face, px},
#include "ryz_v5_font_palette.def"
#undef FONT
};

int main(int argc, char **argv)
{
    assert(argc == 2);
    assert(ryz_font_init() == ESP_OK);
    FILE *out = fopen(argv[1], "wb");
    assert(out);
    fprintf(out, "/* Generated by export_v5_fonts; do not hand-edit.\n"
                 " * Original subset fonts + locked FreeType, uncompressed A8. */\n");
    size_t total_bytes = 0;
    unsigned total_glyphs = 0;
    for (unsigned i = 0; i < sizeof(palette) / sizeof(palette[0]); ++i) {
        ryz_font_metrics_t metrics;
        assert(ryz_font_get_metrics(palette[i].face, palette[i].px, &metrics) == ESP_OK);
        const bool has_degree = ryz_font_supports_codepoint(
            palette[i].face, RYZ_FONT_DEGREE_SIGN);
        const bool has_middle_dot = ryz_font_supports_codepoint(
            palette[i].face, RYZ_FONT_MIDDLE_DOT);
        const unsigned count = 95 + (has_degree || has_middle_dot);
        ryz_font_glyph_t glyphs[97];
        size_t offsets[97], offset = 0;
        fprintf(out, "static const uint8_t bitmap_%u[] = {\n", i);
        for (unsigned g = 0; g < count; ++g) {
            uint8_t bitmap[8192];
            unsigned cp = g < 95 ? g + 0x20 :
                has_degree ? RYZ_FONT_DEGREE_SIGN : RYZ_FONT_MIDDLE_DOT;
            assert(ryz_font_rasterize(palette[i].face, cp, palette[i].px,
                                      bitmap, sizeof(bitmap), &glyphs[g]) == ESP_OK);
            const ryz_font_glyph_t *v = &glyphs[g];
            assert(v->bitmap_bytes == (size_t)v->width * v->height);
            assert(v->advance_x >= 0 && offset + v->bitmap_bytes <= UINT32_MAX);
            offsets[g] = offset;
            fprintf(out, "    /* U+%04X */\n", cp);
            for (size_t b = 0; b < v->bitmap_bytes; ++b) {
                if (b % 24 == 0) fprintf(out, "    ");
                fprintf(out, "%u,", bitmap[b]);
                if (b % 24 == 23 || b + 1 == v->bitmap_bytes) fprintf(out, "\n");
            }
            offset += v->bitmap_bytes;
        }
        fprintf(out, "};\nstatic const v5_glyph_t glyphs_%u[] = {\n", i);
        for (unsigned g = 0; g < count; ++g) {
            const ryz_font_glyph_t *v = &glyphs[g];
            fprintf(out, "    {%zu,%u,%u,%d,%d,%d},\n", offsets[g],
                    v->width, v->height, v->bearing_x,
                    (int)v->bearing_y - v->height, v->advance_x);
        }
        fprintf(out, "};\nstatic const v5_font_data_t data_%u = {glyphs_%u, bitmap_%u, %u, %u};\n",
                i, i, i, count, has_degree ? RYZ_FONT_DEGREE_SIGN :
                has_middle_dot ? RYZ_FONT_MIDDLE_DOT : 0);
        fprintf(out, "static const lv_font_t font_%u = {\n"
                     "    .get_glyph_dsc = glyph_dsc, .get_glyph_bitmap = glyph_bitmap,\n"
                     "    .line_height = %ld, .base_line = %ld,\n"
                     "    .subpx = LV_FONT_SUBPX_NONE, .kerning = LV_FONT_KERNING_NONE,\n"
                     "    .static_bitmap = 1, .underline_position = -1,\n"
                     "    .underline_thickness = 1, .dsc = &data_%u,\n};\n",
                i, (long)metrics.line_height, (long)-metrics.descender, i);
        fprintf(stderr, "face=%d size=%u glyphs=%u bytes=%zu\n",
                palette[i].face, palette[i].px, count, offset);
        total_bytes += offset;
        total_glyphs += count;
    }
    fprintf(out, "static const v5_font_entry_t fonts[] = {\n");
    for (unsigned i = 0; i < sizeof(palette) / sizeof(palette[0]); ++i)
        fprintf(out, "    {%d, %u, &font_%u},\n", palette[i].face, palette[i].px, i);
    fprintf(out, "};\n");
    assert(!ferror(out));
    assert(fclose(out) == 0);
    fprintf(stderr, "EXPORTED fonts=%zu glyphs=%u bitmap_bytes=%zu\n",
            sizeof(palette) / sizeof(palette[0]), total_glyphs, total_bytes);
    return 0;
}
